# Generated by Django 5.2.6 on 2025-09-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(default="default_name", max_length=50),
        ),
    ]
